### ISSUE TITLE
Please add server_key to config/veritrans.yml

### ISSUE THREAD

**Issue by andreasarnold02** [veritrans/veritrans-ruby#17]
Hi,

I want to add veritrans to my rails app and i just generate

rails g veritrans:install

and then edit development secret key and server key from my sanbox.
I tried it in console and it gives me error "Please add server_key to config/veritrans.yml"

```
@result = Veritrans.charge(
  payment_type: "VTWEB",
  transaction_details: {
    order_id: "my-unique-order-id",
    gross_amount: 100_000
  }
)
```

But i have add client key and server key to my sanbox.

Please fix it.
Thanks

**Comment by fauzan182** [comment]
please add file veritrans.rb to folder 'config/initializers'
it looks like something like this..


```ruby
Veritrans.setup do
  config.load_config Rails.root.join("config/veritrans.yml")

  # Or set it manually...
  # config.server_key = ""
  # config.client_key = ""
  # config.api_host = ""

  # Veritrans::Events is rack application to handle http notifications from Veritrans
  # To enable it, add in config/routes.rb
  # mount Veritrans::Events.new => '/vt_events'

  # All possible events:
  #
  # * payment.success     == ['authorize', 'capture', 'settlement']
  # * payment.failed      == ['deny', 'canel', 'expire']
  # * payment.challenge   # when payment.froud_status == 'challenge'
  #
  # * payment.authorize
  # * payment.capture
  # * payment.settlement
  # * payment.deny
  # * payment.canel
  # * payment.expire

  # events.subscribe 'payment.success' do |payment|
  #   payment.mark_paid!
  # end
  # 
  # events.subscribe 'payment.failed' do |payment|
  #   payment.mark_failed!
  # end
  # 
  # events.subscribe 'payment.challenge' do |payment|
  #   payment.mark_challenge!
  # end
  # 
  # events.subscribe /.+/ do |payment, event_name|
  #   p "Event: #{event_name}"
  #   p payment
  # end

end
```

**Comment by andreasarnold02** [comment]
When first generate
` ` `
rails g veritrans:install
` ` `
it will automatically generate veritrans.rb in 'config/initializers', wont it ?

I have tried set manual server key and client key in config/initializer/veritrans.rb but still the same.

**Comment by Paxa** [comment]
How did you try it in console?

**Comment by andreasarnold02** [comment]
I tried this in console

` ` `
@result = Veritrans.charge(
  payment_type: "VTWEB",
  transaction_details: {
    order_id: "my-unique-order-id",
    gross_amount: 100_000
  }
)
` ` `

and it give me this "Please add server_key to config/veritrans.yml"

**Comment by andreasarnold02** [comment]
I'm sorry.
I didnt change anything and it sudenly sent sucess callback.

Thank you for the respon

**Comment by Paxa** [comment]
I think you using gem spring, which come with rails 4 by default, and it
requires to restart spring when you change config file. Anyway glad it works
