### ISSUE TITLE
Please push 2.2.0 to Rubygems

### ISSUE THREAD

**Issue by firewalker06** [veritrans/veritrans-ruby#26]
Current version of `veritrans` gem still uses version `2.1.3`:

<img width="400" alt="screen shot 2017-06-16 at 2 50 37 pm" src="https://user-images.githubusercontent.com/157515/27217228-342957bc-52a3-11e7-9422-18ac02065a78.png">

**Comment by Paxa** [comment]
Done, @firewalker06 thank you for noticing

**Comment by firewalker06** [comment]
Awesome :ok_man:
