### ISSUE TITLE
Remove Using server key logging?

### ISSUE THREAD

**Issue by fikrikarim** [veritrans/veritrans-ruby#31]
Hello, I just tried Midtrans and so far it's amazing. One concern I have is why do we need to log server keys everytime we make a request?

AFAIK isn't it a best practice not to store sensitive informations on logs including a secret key? For example Rails automatically remove password from logs. So I'm interested on any reason for this. Thanks!

**Comment by Paxa** [comment]
That happen by mistake, will try to fix it

**Comment by fikrikarim** [comment]
Alright thank you very much! I can also submit a pull request if you prefer, just let me know the directions or the specs 👍

**Comment by Paxa** [comment]
This should fix it https://github.com/veritrans/veritrans-ruby/commit/f02a8516d3c8a5ddad3913ad86408cdd950b9dc7

You may use this gem from git:
```ruby
gem 'veritrans', github: 'veritrans/veritrans-ruby'
```
or wait a little till I fix tests in CI and push new version

**Comment by Paxa** [comment]
Pushed version 2.3.0

**Comment by fikrikarim** [comment]
Alright thank you! 👍
