### ISSUE TITLE
Invalid JSON format or header Veritrans.status(order_id)

### ISSUE THREAD

**Issue by muhammadyana** [veritrans/veritrans-ruby#33]
Hello, i get error when running `Veritrans.status(order_id)` full error messages is
`<Veritrans::Result:70149847420880 ^^ status: 200 time: 234ms ^^ data: {status_code: "403", status_message: "Invalid JSON format or header"}>`
in previous mount i try it normal, but today i'm getting error

Thanks

**Comment by rizdaprasetya** [comment]
403 which is forbidden can be caused by your internal network having firewall that reject your API call. Please try to check your network firewall or use other network.

**Comment by tiaraitalyana** [comment]
Hello, i get the error too, full messages ```"status_code" : "403", "status_message" : "Invalid JSON format or header"```

**Comment by rizdaprasetya** [comment]
Hi @tiaraitalyana after some investigation, looks like there's possibility of `403` will be returned for `Veritrans.status(order_id)` incase of `order_id` is not found on Midtrans side (not valid transaction). The solution is to check the `order_id` being used and make sure it is correct.

Can you provide the value of `order_id` (or parameter) you used on `.status(...)` function call?

\*This is likely due to unexpected behaviour `excon` http client used in this library which send double `Accept : ...` header, and then API server return 403 in case of wrong parameter for get status.

**Comment by nuclearthinker** [comment]
Is it resolved? 
I have similar error message in Veritrans.charge() function for payment with permata VA, other payment_type successful as expected. I wonder why only permata VA which has not worked properly. I have inspected files inside lib folder in this repository, but I couldn't get any clue about this error. @rizdaprasetya

**Comment by rizdaprasetya** [comment]
Looks like this is some issue on Excon (HTTP library used on this lib)
A) **[Sample issue]** using these config:
```
request_options = {
        :path => URI.parse(url).path,
        :headers => {
          :Authorization => auth_header || basic_auth_header(config.server_key),
          :Accept => "application/json",
          :"Content-Type" => "application/json",
          :"User-Agent" => "Veritrans ruby gem #{Veritrans::VERSION}"
        }
      }
```
resulted in HTTP request with double `Accept` header:
```
POST /v2/charge HTTP/1.1
User-Agent: excon/0.70.0
Accept: */*
Accept: application/json
```
Which cause API server to fail to parse JSON, which response `status_code" : "403", "status_message" : "Invalid JSON format or header"`
Demo: https://repl.it/repls/JovialAggravatingOs

B) **[Sample fixed]** While using these config:
```
request_options = {
        :path => URI.parse(url).path,
        :headers => {
          "Authorization" => auth_header || basic_auth_header(config.server_key),
          "Accept" => "application/json",
          "Content-Type" => "application/json",
          "User-Agent" => "Veritrans ruby gem #{Veritrans::VERSION}"
        }
      }
```
Result in HTTP request with proper `Accept` header (only 1).
Which will be able to be parsed by API, and API will response correctly.
Demo: https://repl.it/repls/BelatedDarkblueCoins

Will try to create PR to fix it as described on point B.
