### ISSUE TITLE
Inconsistent error message thrown

### ISSUE THREAD

**Issue by rizdaprasetya** [veritrans/veritrans-ruby#74]
This line throws lack of `API response` on the err msg
https://github.com/veritrans/veritrans-ruby/blob/916b1cbb66cc7dd97ec722d4cdc329d384209aae/lib/veritrans/client.rb#L129

Should have throw consistent err msg with this line
https://github.com/veritrans/veritrans-ruby/blob/916b1cbb66cc7dd97ec722d4cdc329d384209aae/lib/veritrans/client.rb#L139

**Comment by rizdaprasetya** [comment]
Can also refer to this as example 
https://github.com/Midtrans/midtrans-nodejs-client/blob/bd7ad516f13c08c88847bff6c8962ab1fac55487/lib/httpClient.js#L71-L90

**Comment by Andrenzo17** [comment]
Thank you for finding and example kak,
i have done to fix the inconsitent error message
https://github.com/veritrans/veritrans-ruby/commit/13d4791f9efebd47bdcac6f086daa706c24326f6
