### ISSUE TITLE
Readme file lack of proper info on how to switch to Produnction env

### ISSUE THREAD

**Issue by rizdaprasetya** [veritrans/veritrans-ruby#75]
Since the readme only mentioned
```
Midtrans.config.api_host = "https://api.sandbox.midtrans.com"
```
Looks like how to change env on this library is to change API url, unlike other Midtrans library which simply use true/false value.

In this case, there is not enough info on how to switch to Production env. What is the value for production env? how to switch to it? This should be properly documented.

**Comment by Andrenzo17** [comment]
Thank you for feedback kak, 
i have add section how to switch in production.

1. Change api_host URL from https://api.sandbox.midtrans.com to https://api.midtrans.com.
2. Use Client Key and Server Key for Production environment. For more details, refer to Retrieving API Access Keys.

https://github.com/veritrans/veritrans-ruby#22-client-initialization-and-configuration
