### ISSUE TITLE
Add integration with Pay gem

### ISSUE THREAD

**Issue by kwhandy** [veritrans/veritrans-ruby#81]
Hi guys, I just open an [issue/feature request](https://github.com/pay-rails/pay/issues/663) to add Midtrans to Pay gem that managed by @excid3. so, I would expect some assistance from Midtrans's team for this request. or any idea about this?

**Comment by Andrenzo17** [comment]
Hi @kwhandy i have checked Pay gem looks like using ruby on rails. 

Currently Midtrans team only maintain Ruby without framework Ruby on Rails and Sinatra. 
I think if you request feature on Pay gem Github, you can wait for their response.

Thank you

**Comment by kwhandy** [comment]
I see, but they might need Midtrans team support to access MAP in sandbox or production mod since they are not Indonesian if they decide to execute this integration.

So should I leave this issue open or close?

**Comment by Andrenzo17** [comment]
If they need documentation to access Midtrans Dashboard you can give them this doc. https://docs.midtrans.com/en/midtrans-account/overview
https://docs.midtrans.com/en/technical-reference/sandbox-test

You can close this open issue.
Thank you

**Comment by kwhandy** [comment]
Ok thanks!
